
#ifndef SORTS_BITONIC_SORT_H
#define SORTS_BITONIC_SORT_H

#define BITONIC_THREADS_POW 10
#define BITONIC_THREADS (1 << BITONIC_THREADS_POW)
#define BITONIC_BLOCK (2* BITONIC_THREADS)
void bitonic_sort(int *, int);

#endif //SORTS_BITONIC_SORT_H