//
// Created by Miron Ficak on 09/07/2017.
//


#include <climits>
#include <cstdio>

#ifndef SORTS_SAMPLE_RAND_H
#define SORTS_SAMPLE_RAND_H

#define ELEMENTS_PER_THREAD 8
#define S_POW 7
#define S_SIZE (1 << S_POW)
#define AS 30

#define THREADS_POW 10
#define THREADS_PER_BLOCK (1 << THREADS_POW)

#define MAX_SAMPLE_SIZE 131072


#define ARRAYS_NUM 8
#define BLOCK_SIZE (THREADS_PER_BLOCK * ELEMENTS_PER_THREAD)

//#define M BLOCK_SIZE
#define SAMPLE_OHTER_SORT_LIM_POW 14
#define SAMPLE_OTHER_SORT_LIM (1 << SAMPLE_OHTER_SORT_LIM_POW)

#define PREFSUM_THREADS 1024
#define PREFSUM_ELEMENTS_PER_THREAD 2
#define PREFSUM_BLOCK_SIZE (PREFSUM_THREADS * PREFSUM_ELEMENTS_PER_THREAD)

#define SAMPLE_BLOCK (AS*S_SIZE)
#define SAMPLE_THREADS 1024

void sampleRand(int *, int);


#endif //SORTS_SAMPLE_RAND_H
